### PR TITLE
add TLSHandshakeTimeout, add Dialer KeepAlive

### PR DESCRIPTION
**Pull request by nickvanw**
This brings in the `TLSHandshakeTimeout` param from `http.Transport`, as well as allowing configuration of the dialer `KeepAlive`

### CODE REVIEW

**Comment by mreiferson** [comment]
hi @nickvanw, thanks - these are welcome changes.

Ideally we would use Go's build tags to segment this functionality and allow the library to support older versions of Go.

I'm torn however, as I've been wanting to remove the `Close()` method too, since it's no longer used.

Thoughts?

**Comment by nickvanw** [comment]
Hi @mreiferson!

I'd be happy to use the build tags here to enable backwards compatibility! I'm not sure what version the `TLSHandshakeTimeout` came in, but I think it was early 2014? 

That being said, if there's other things that are breaking, I definitely agree that now might be a good time to make breaking changes - having a noop method in there is pretty annoying. 

Ultimately, it's up to you, but I think either direction is good!

**Comment by mreiferson** [comment]
I think I'm OK with moving forward, we can always tag the last compatible release for pinning versions or vendoring.

**Comment by mreiferson** [comment]
specifically, let's add a build tag for whatever release added the features we needed and also drop the `Close` method

**Comment by nickvanw** [comment]
Awesome! Looks like `TLSHandshakeTimeout` was added in go 1.3, are we cool with requiring the latest version?

**Comment by mreiferson** [comment]
you mean `go 1.4`?  If it only requires `go 1.3` then I think that would make more sense?

**Pull request closed without merging**
